from __future__ import annotations

from typing import Any, Dict, Optional

from pydantic import ConfigDict, Field

from core.domain.entities.base_entity import MongoEntity


class TradeSignalEntity(MongoEntity):
    """
    Canonical trade signal entity persisted after evaluation.

    Signals are generated by api-signals and later consumed by the
    trade execution pipeline.
    """

    strategy_id: str
    stream_key: str
    symbol: str
    interval: str
    ts: int

    signal_type: str
    status: str = "PENDING"

    idempotency_key: str
    payload: Dict[str, Any] = Field(default_factory=dict)

    attempts: int = 0
    last_error: Optional[str] = None
    execution_response: Optional[Dict[str, Any]] = None

    model_config = ConfigDict(extra="ignore")