from __future__ import annotations

from enum import Enum


class TradeStrategyType(str, Enum):
    """
    Supported trade strategy types.
    """

    ATR_TWO_STAGE = "atr_two_stage"


class TradeStrategyStatus(str, Enum):
    """
    Lifecycle status for trade strategies.
    """

    ACTIVE = "ACTIVE"
    INACTIVE = "INACTIVE"


class TradeSignalStatus(str, Enum):
    """
    Execution status for generated trade signals.
    """

    PENDING = "PENDING"
    SENT = "SENT"
    FAILED = "FAILED"


class TradeSignalType(str, Enum):
    """
    Trade signal actions generated by strategy evaluation.
    """

    OPEN_LONG = "OPEN_LONG"
    OPEN_SHORT = "OPEN_SHORT"
    CLOSE_LONG = "CLOSE_LONG"
    CLOSE_SHORT = "CLOSE_SHORT"
    CLOSE_POSITION = "CLOSE_POSITION"


class TradePositionSide(str, Enum):
    """
    Hedge-mode position side used by the trade flow.
    """

    LONG = "LONG"
    SHORT = "SHORT"


class TradeRuntimeState(str, Enum):
    """
    Current operational runtime state of the strategy.
    """

    FLAT = "FLAT"
    ARMED = "ARMED"
    OPEN_LONG = "OPEN_LONG"
    OPEN_SHORT = "OPEN_SHORT"


class TradeEvent(str, Enum):
    """
    Internal strategy events emitted while evaluating candles.
    """

    ARM_ON_LOW_ATR = "ARM_ON_LOW_ATR"
    ATR_LOW_EXIT = "ATR_LOW_EXIT"
    OPEN_LONG = "OPEN_LONG"
    OPEN_SHORT = "OPEN_SHORT"
    MAX_LOSS_STOP = "MAX_LOSS_STOP"
    REGIME_BLOCKED_LONG = "REGIME_BLOCKED_LONG"
    REGIME_BLOCKED_SHORT = "REGIME_BLOCKED_SHORT"


class TradeExecutionTarget(str, Enum):
    """
    Supported execution backends for trade signals.
    """

    API_TRADE_EXECUTION = "api-trade-execution"


class TradeAtrThresholdMode(str, Enum):
    """
    Threshold mode used for ATR comparisons.
    """

    ATR = "atr"
    ATR_PCT = "atr_pct"


class TradeAtrThresholdSource(str, Enum):
    """
    Source of the active ATR thresholds used for the current candle.
    """

    FIXED = "fixed"
    DYNAMIC = "dynamic"


class TradeMode(str, Enum):
    """
    Trading side policy used by the ATR two-stage strategy.
    """

    FLIP = "flip"
    LONG_ONLY = "long_only"
    SHORT_ONLY = "short_only"
    FLAT_ON_DOWN = "flat_on_down"


class TradeMovingAverageType(str, Enum):
    """
    Moving-average type used by regime filters.
    """

    EMA = "ema"
    SMA = "sma"